import { PrismaClient } from '@prisma/client'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const prisma = new PrismaClient() as any

async function main() {
  console.log('Seeding menu items...')

  // Clear existing items first so we get a clean slate
  await prisma.menuItem.deleteMany({})

  await prisma.menuItem.createMany({
    data: [
      // ── SOUPS ──
      { id:'s1',  name:'Egusi Soup',                price:35000, category:'Soups',         subcat:null,    description:'Rich ground melon seed soup with assorted meats & stockfish. Served in a generous 2L bowl.', badge:'2L Bowl',     badgeColor:null,      note:null,               imgUrl:'/soup/egusi.jpg',                                                                          img2Url:null,                                                                              sortOrder:1  },
      { id:'s2',  name:'Oha Soup',                  price:35000, category:'Soups',         subcat:null,    description:'Delicate Igbo soup made with fresh oha leaves, cocoyam, and assorted proteins.',             badge:'2L Bowl',     badgeColor:null,      note:null,               imgUrl:'/soup/oha-1.jpg',                                                                          img2Url:'/soup/oha-2.jpg',                                                                 sortOrder:2  },
      { id:'s3',  name:'Bitterleaf Soup',           price:35000, category:'Soups',         subcat:null,    description:'Classic wrung bitterleaf soup with cocoyam, palm oil and assorted meat.',                    badge:'2L Bowl',     badgeColor:null,      note:null,               imgUrl:'/soup/bitterleaf.jpg',                                                                     img2Url:null,                                                                              sortOrder:3  },
      { id:'s4',  name:'Ogbono Soup',               price:35000, category:'Soups',         subcat:null,    description:'Sticky, flavourful draw soup made from ground ogbono seeds with leafy vegetables.',          badge:'2L Bowl',     badgeColor:null,      note:null,               imgUrl:'/soup/ogbono.jpg',                                                                         img2Url:null,                                                                              sortOrder:4  },
      { id:'s5',  name:'Uziza Soup',                price:35000, category:'Soups',         subcat:null,    description:'Aromatic pepper soup with uziza leaves and a blend of traditional spices.',                  badge:'2L Bowl',     badgeColor:null,      note:null,               imgUrl:'/soup/uziza.jpg',                                                                          img2Url:null,                                                                              sortOrder:5  },
      { id:'s6',  name:'Banga Soup',                price:35000, category:'Soups',         subcat:null,    description:'Delta-style palm nut soup with its distinct sweet-spicy flavour profile.',                   badge:'2L Bowl',     badgeColor:null,      note:null,               imgUrl:'/soup/banga.jpg',                                                                          img2Url:null,                                                                              sortOrder:6  },
      { id:'s7',  name:'Eforiro',                   price:35000, category:'Soups',         subcat:null,    description:'Yoruba mixed vegetable soup with fluted pumpkin, locust beans and assorted meat.',           badge:'2L Bowl',     badgeColor:null,      note:null,               imgUrl:'/soup/eforiro-1.jpg',                                                                      img2Url:'/soup/eforiro-2.jpg',                                                             sortOrder:7  },
      { id:'s8',  name:'Afang Soup',                price:37000, category:'Soups',         subcat:null,    description:'Cross River prized soup with afang leaves, waterleaf, and periwinkle.',                      badge:'2L Bowl',     badgeColor:'#8B5CF6', note:null,               imgUrl:'/soup/afang.jpg',                                                                          img2Url:null,                                                                              sortOrder:8  },
      { id:'s9',  name:'Edikang Ikong',             price:37000, category:'Soups',         subcat:null,    description:'Premium Nigerian vegetable soup with ugu and waterleaf. Rich, thick and deeply satisfying.',  badge:'2L Bowl',     badgeColor:'#8B5CF6', note:null,               imgUrl:'/soup/edikang-ikong.jpg',                                                                  img2Url:'/food/edikang-ikong-2.jpg',                                                       sortOrder:9  },
      { id:'s10', name:'Black Soup',                price:35000, category:'Soups',         subcat:null,    description:'Unique Edo black soup made from orogbo and efinrin leaves with a bold earthy taste.',        badge:'2L Bowl',     badgeColor:null,      note:null,               imgUrl:'/soup/black-soup.jpg',                                                                     img2Url:null,                                                                              sortOrder:10 },
      { id:'s11', name:'Atama Soup',                price:40000, category:'Soups',         subcat:null,    description:'Ibibio specialty soup with atama leaves and fresh palm nut extract.',                        badge:'2L Bowl',     badgeColor:'#D97706', note:null,               imgUrl:'/soup/atama.jpg',                                                                          img2Url:null,                                                                              sortOrder:11 },
      { id:'s12', name:'Nsala (White Soup)',        price:40000, category:'Soups',         subcat:null,    description:'Light, peppery Anambra soup made without palm oil. Perfect with fufu or pounded yam.',      badge:'2L Bowl',     badgeColor:'#D97706', note:null,               imgUrl:'/soup/nsala.jpg',                                                                          img2Url:null,                                                                              sortOrder:12 },
      { id:'s13', name:'Ofe Owerri',               price:65000, category:'Soups',         subcat:null,    description:'Premium Imo State soup — a luxurious blend of oha, cocoyam and assorted meats.',            badge:'Premium',     badgeColor:'#DC2626', note:null,               imgUrl:'/soup/ofe-owerri.jpg',                                                                     img2Url:null,                                                                              sortOrder:13 },
      { id:'s14', name:'Seafood Okro',              price:70000, category:'Soups',         subcat:null,    description:'Our showstopper — loaded okro soup with prawns, crab, fish, and calamari.',                 badge:'Signature',   badgeColor:'#DC2626', note:null,               imgUrl:'/soup/seafood-okro.jpg',                                                                   img2Url:'/soup/okra.jpg',                                                                  sortOrder:14 },

      // ── STEWS ──
      { id:'st1', name:'Chicken Stew',              price:30000, category:'Stews',         subcat:null,    description:'Rich tomato-based stew slow-cooked with succulent pieces of chicken. 2L bowl.',             badge:'2L Bowl',     badgeColor:null,      note:null,               imgUrl:'/stew/chicken-stew-1.jpg',                                                                 img2Url:'/stew/chicken-stew-2.jpg',                                                        sortOrder:15 },
      { id:'st2', name:'Beef Stew',                 price:30000, category:'Stews',         subcat:null,    description:'Classic Nigerian beef stew with blended tomatoes and aromatic spices. 2L bowl.',             badge:'2L Bowl',     badgeColor:null,      note:null,               imgUrl:'/stew/beef-stew-1.jpg',                                                                    img2Url:'/stew/beef-stew-2.jpg',                                                           sortOrder:16 },
      { id:'st3', name:'Fish Stew',                 price:35000, category:'Stews',         subcat:null,    description:'Tomato-based stew with fresh, well-seasoned fish pieces. 2L bowl.',                         badge:'2L Bowl',     badgeColor:null,      note:null,               imgUrl:'/stew/fish-stew-1.jpg',                                                                    img2Url:null,                                                                              sortOrder:17 },
      { id:'st4', name:'Ofada Sauce',               price:45000, category:'Stews',         subcat:null,    description:'Authentic Ofada sauce with ayamase pepper blend. Perfect with ofada rice. 2L bowl.',        badge:'Fan Fav',     badgeColor:'#F97316', note:null,               imgUrl:'/stew/ofada-sauce-1.jpg',                                                                  img2Url:'/stew/ofada-sauce-2.jpg',                                                         sortOrder:18 },
      { id:'st5', name:'Ofe Akwu (Banga Stew)',    price:35000, category:'Stews',         subcat:null,    description:'Palm nut stew Urhobo style — great with boiled rice or yam. 2L bowl.',                     badge:'2L Bowl',     badgeColor:null,      note:null,               imgUrl:'/stew/ofe-akwu-1.jpg',                                                                     img2Url:null,                                                                              sortOrder:19 },

      // ── RICE & POTTAGE ──
      { id:'r1',  name:'Smokey Jollof Rice (3L)',   price:22000, category:'Rice & Pottage',subcat:null,    description:'Our signature smokey party jollof — 3 litres with 5 pcs beef/chicken included.',            badge:'Bestseller',  badgeColor:'#F97316', note:'Includes 5pcs beef/chicken', imgUrl:'/food/smokey-jollof.jpg',                                                             img2Url:'/food/jollof-rice-bowl.jpg',                                                      sortOrder:20 },
      { id:'r2',  name:'Smokey Jollof Rice (5L)',   price:35000, category:'Rice & Pottage',subcat:null,    description:'Party size jollof rice — 5 litres with 5 pcs beef/chicken. Feeds a crowd.',                 badge:'Party Size',  badgeColor:'#8B5CF6', note:'Includes 5pcs beef/chicken', imgUrl:'/food/jollof-rice-bowl.jpg',                                                          img2Url:'/food/smokey-jollof.jpg',                                                         sortOrder:21 },
      { id:'r3',  name:'Fried Rice (3L)',            price:28000, category:'Rice & Pottage',subcat:null,    description:'Wok-fried Nigerian fried rice loaded with vegetables and protein. 3 litres.',               badge:null,          badgeColor:null,      note:'Includes 5pcs beef/chicken', imgUrl:'/food/fried-rice-1.jpg',                                                              img2Url:'/food/fried-rice-2.jpg',                                                          sortOrder:22 },
      { id:'r4',  name:'Fried Rice (5L)',            price:40000, category:'Rice & Pottage',subcat:null,    description:'Large portion wok-fried rice for events. 5 litres with protein.',                           badge:'Party Size',  badgeColor:'#8B5CF6', note:'Includes 5pcs beef/chicken', imgUrl:'/food/fried-rice-2.jpg',                                                              img2Url:'/food/fried-rice-1.jpg',                                                          sortOrder:23 },
      { id:'r5',  name:"Eddy's Pottage (3L)",       price:15000, category:'Rice & Pottage',subcat:null,    description:"Our chef's signature yam pottage — 3 litres, slow-cooked with panla fish.",                 badge:'Chef Special',badgeColor:'#D97706', note:'Includes 5pcs panla fish',   imgUrl:'https://images.unsplash.com/photo-1600335895229-6e75511892c8?w=600&q=80',           img2Url:null,                                                                              sortOrder:24 },

      // ── PASTA & RICE ──
      { id:'p1',  name:'Creamy Chicken Pasta',      price:12000, category:'Pasta & Rice',  subcat:'Pasta', description:'Silky cream sauce, perfectly seasoned chicken — Italian comfort with Nigerian soul.',        badge:'Popular',     badgeColor:'#F97316', note:null,               imgUrl:'/food/creamy-chicken-pasta-1.jpg',                                                         img2Url:'/food/creamy-chicken-pasta-2.jpg',                                                sortOrder:25 },
      { id:'p2',  name:'Nigerian Jollof Spaghetti', price:9000,  category:'Pasta & Rice',  subcat:'Pasta', description:'Smokey jollof-seasoned spaghetti with juicy chicken on the side.',                          badge:null,          badgeColor:null,      note:null,               imgUrl:'/food/jollof-spag-1.jpg',                                                                  img2Url:'/food/jollof-spag-2.jpg',                                                         sortOrder:26 },
      { id:'p3',  name:'Shrimp Pasta',              price:15000, category:'Pasta & Rice',  subcat:'Pasta', description:'Plump shrimp in a rich buttery sauce over perfectly cooked pasta.',                         badge:null,          badgeColor:null,      note:null,               imgUrl:'/food/shrimp-pasta-1.jpg',                                                                 img2Url:'/food/shrimp-pasta-2.jpg',                                                        sortOrder:27 },
      { id:'p4',  name:'Asun Pasta',                price:12000, category:'Pasta & Rice',  subcat:'Pasta', description:'Smokey peppered goat meat tossed with pasta — bold Lagos flavours.',                        badge:'Spicy 🌶',   badgeColor:'#DC2626', note:null,               imgUrl:'/food/asun-pasta-1.jpg',                                                                   img2Url:'/food/asun-pasta-2.jpg',                                                          sortOrder:28 },
      { id:'p5',  name:'Basmati Jollof Rice',       price:9000,  category:'Pasta & Rice',  subcat:'Rice',  description:'Aromatic long-grain basmati in signature jollof sauce with chicken.',                       badge:null,          badgeColor:null,      note:null,               imgUrl:'/food/basmati-jollof.jpg',                                                                 img2Url:'/food/jollof-rice-bowl.jpg',                                                      sortOrder:29 },
      { id:'p6',  name:'Special Basmati Fried Rice',price:12000, category:'Pasta & Rice',  subcat:'Rice',  description:'Wok-tossed basmati with mixed vegetables, egg and chicken.',                                badge:null,          badgeColor:null,      note:null,               imgUrl:'/food/basmati-fried-rice.jpg',                                                             img2Url:'/food/seafood-fried-rice.jpg',                                                    sortOrder:30 },
      { id:'p7',  name:'Basmati Coconut Rice',      price:12000, category:'Pasta & Rice',  subcat:'Rice',  description:'Creamy coconut-infused basmati with perfectly seasoned chicken.',                           badge:null,          badgeColor:null,      note:null,               imgUrl:'/food/coconut-rice.jpg',                                                                   img2Url:'/food/basmati-rice.jpg',                                                          sortOrder:31 },
      { id:'p8',  name:'Native Nigerian Rice',      price:9000,  category:'Pasta & Rice',  subcat:'Rice',  description:'Traditional ofada-style rice with rich palm oil sauce and assorted.',                       badge:null,          badgeColor:null,      note:null,               imgUrl:'/food/native-rice.jpg',                                                                    img2Url:null,                                                                              sortOrder:32 },
      { id:'p9',  name:'Spicy Asun Rice',           price:9000,  category:'Pasta & Rice',  subcat:'Rice',  description:'Jollof rice crowned with smoky peppered asun goat meat.',                                   badge:'Spicy 🌶',   badgeColor:'#DC2626', note:null,               imgUrl:'/food/spicy-asun-rice.jpg',                                                                img2Url:'/food/asun-rice.jpg',                                                             sortOrder:33 },

      // ── FOOD BOXES ──
      { id:'b1',  name:'Classic Box',               price:15000, category:'Food Boxes',    subcat:null,    description:'A hearty classic box — your choice of protein with rice or swallow and a side.',            badge:null,          badgeColor:null,      note:null,               imgUrl:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80',          img2Url:'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80',            sortOrder:34 },
      { id:'b2',  name:'Deluxe Box',                price:30000, category:'Food Boxes',    subcat:null,    description:'Premium proteins, extra sides and a refreshing drink included.',                            badge:'Popular',     badgeColor:'#F97316', note:null,               imgUrl:'/package/deluxe-box-1.jpg',                                                                img2Url:'/package/deluxe-box-2.jpg',                                                       sortOrder:35 },
      { id:'b3',  name:'Premium Box',               price:45000, category:'Food Boxes',    subcat:null,    description:'Our finest box — large portions, premium cuts, dessert included.',                          badge:'Best Value',  badgeColor:'#D97706', note:null,               imgUrl:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=80',          img2Url:'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=600&q=80',         sortOrder:36 },
      { id:'b4',  name:'Breakfast Box',             price:28000, category:'Food Boxes',    subcat:null,    description:'Start your morning right — eggs, bread, sausage, plantain and fresh juice.',               badge:'Morning ☀️', badgeColor:'#F59E0B', note:null,               imgUrl:'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=600&q=80',          img2Url:'https://images.unsplash.com/photo-1543352634-99a5d50ae78e?w=600&q=80',            sortOrder:37 },
      { id:'b5',  name:'Treat Box',                 price:20000, category:'Food Boxes',    subcat:null,    description:'Special curated box — perfect for gifting or treating yourself.',                           badge:null,          badgeColor:null,      note:null,               imgUrl:'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&q=80',             img2Url:'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=600&q=80',         sortOrder:38 },
      { id:'b6',  name:'Moimoi in Leaves (12pcs)',  price:18000, category:'Food Boxes',    subcat:null,    description:'12 pieces of authentic leaf-wrapped moimoi with egg or fish inside.',                       badge:null,          badgeColor:null,      note:'With egg or fish', imgUrl:'/package/moimoi-1.jpg',                                                                    img2Url:null,                                                                              sortOrder:39 },
      { id:'b7',  name:'Lunch Pack – Mini',         price:4500,  category:'Food Boxes',    subcat:null,    description:'Mini lunch pack — great for office orders. Minimum 6 packs.',                               badge:'Bulk Order',  badgeColor:null,      note:'Min. 6 packs',     imgUrl:'/package/lunch-mini-1.jpg',                                                                img2Url:null,                                                                              sortOrder:40 },
      { id:'b8',  name:'Lunch Pack – Regular',      price:7000,  category:'Food Boxes',    subcat:null,    description:'Regular lunch pack with satisfying portions. Minimum 6 packs.',                             badge:'Bulk Order',  badgeColor:null,      note:'Min. 6 packs',     imgUrl:'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=600&q=80',          img2Url:'https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?w=600&q=80',         sortOrder:41 },
      { id:'b9',  name:'Small Chops Pack',          price:3500,  category:'Food Boxes',    subcat:null,    description:'Assorted small chops — puff puff, spring rolls, samosa. Min. 6 packs.',                    badge:null,          badgeColor:null,      note:'Min. 6 packs',     imgUrl:'https://images.unsplash.com/photo-1506354666786-959d6d497f1a?w=600&q=80',          img2Url:'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&q=80',            sortOrder:42 },
    ],
  })

  console.log('✅ Seeded 43 menu items successfully!')
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())