import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding menu items...')
  await prisma.menuItem.deleteMany({})

  await prisma.menuItem.createMany({
    data: [
      // ── SOUPS (1–14) ───────────────────────────────────────────────────
      { id:'1',  name:'Egusi Soup',           price:35000, category:'Soups', description:'Rich ground melon seed soup with assorted meats & stockfish. Served in a generous 2L bowl.', badge:'2L Bowl',    badgeColor:null,      imgUrl:'/soup/egusi.jpg',          sortOrder:1  },
      { id:'2',  name:'Oha Soup',             price:35000, category:'Soups', description:'Delicate Igbo soup made with fresh oha leaves, cocoyam, and assorted proteins.',             badge:'2L Bowl',    badgeColor:null,      imgUrl:'/soup/oha-1.jpg',          img2Url:'/soup/oha-2.jpg',           sortOrder:2  },
      { id:'3',  name:'Bitterleaf Soup',      price:35000, category:'Soups', description:'Classic wrung bitterleaf soup with cocoyam, palm oil and assorted meat.',                    badge:'2L Bowl',    badgeColor:null,      imgUrl:'/soup/bitterleaf.jpg',     sortOrder:3  },
      { id:'4',  name:'Ogbono Soup',          price:35000, category:'Soups', description:'Sticky, flavourful draw soup made from ground ogbono seeds with leafy vegetables.',          badge:'2L Bowl',    badgeColor:null,      imgUrl:'/soup/ogbono.jpg',         sortOrder:4  },
      { id:'5',  name:'Uziza Soup',           price:35000, category:'Soups', description:'Aromatic pepper soup with uziza leaves and a blend of traditional spices.',                  badge:'2L Bowl',    badgeColor:null,      imgUrl:'/soup/uziza.jpg',          sortOrder:5  },
      { id:'6',  name:'Banga Soup',           price:35000, category:'Soups', description:'Delta-style palm nut soup with its distinct sweet-spicy flavour profile.',                   badge:'2L Bowl',    badgeColor:null,      imgUrl:'/soup/banga.jpg',          sortOrder:6  },
      { id:'7',  name:'Eforiro',              price:35000, category:'Soups', description:'Yoruba mixed vegetable soup with fluted pumpkin, locust beans and assorted meat.',           badge:'2L Bowl',    badgeColor:null,      imgUrl:'/soup/eforiro-1.jpg',      img2Url:'/soup/eforiro-2.jpg',       sortOrder:7  },
      { id:'8',  name:'Afang Soup',           price:37000, category:'Soups', description:'Cross River prized soup with afang leaves, waterleaf, and periwinkle.',                      badge:'2L Bowl',    badgeColor:'#8B5CF6', imgUrl:'/soup/afang.jpg',          sortOrder:8  },
      { id:'9',  name:'Edikang Ikong',        price:37000, category:'Soups', description:'Premium Nigerian vegetable soup with ugu and waterleaf. Rich, thick and deeply satisfying.',  badge:'2L Bowl',    badgeColor:'#8B5CF6', imgUrl:'/soup/edikang-ikong.jpg',  sortOrder:9  },
      { id:'10', name:'Black Soup',           price:35000, category:'Soups', description:'Unique Edo black soup made from orogbo and efinrin leaves with a bold earthy taste.',        badge:'2L Bowl',    badgeColor:null,      imgUrl:'/soup/black-soup.jpg',     sortOrder:10 },
      { id:'11', name:'Atama Soup',           price:40000, category:'Soups', description:'Ibibio specialty soup with atama leaves and fresh palm nut extract.',                        badge:'2L Bowl',    badgeColor:'#D97706', imgUrl:'/soup/atama.jpg',          sortOrder:11 },
      { id:'12', name:'Nsala (White Soup)',   price:40000, category:'Soups', description:'Light, peppery Anambra soup made without palm oil. Perfect with fufu or pounded yam.',      badge:'2L Bowl',    badgeColor:'#D97706', imgUrl:'/soup/nsala.jpg',          sortOrder:12 },
      { id:'13', name:'Ofe Owerri',           price:65000, category:'Soups', description:'Premium Imo State soup — a luxurious blend of oha, cocoyam and assorted meats.',            badge:'Premium',    badgeColor:'#DC2626', imgUrl:'/soup/ofe-owerri.jpg',     sortOrder:13 },
      { id:'14', name:'Seafood Okro',         price:70000, category:'Soups', description:'Our showstopper — loaded okro soup with prawns, crab, fish, and calamari.',                 badge:'Signature',  badgeColor:'#DC2626', imgUrl:'/soup/seafood-okro.jpg',   img2Url:'/soup/okra.jpg',            sortOrder:14 },

      // ── STEWS (15–19) ──────────────────────────────────────────────────
      { id:'15', name:'Chicken Stew',         price:30000, category:'Stews', description:'Rich tomato-based stew slow-cooked with succulent pieces of chicken. 2L bowl.',             badge:'2L Bowl',    badgeColor:null,      imgUrl:'/stew/chicken-stew-1.jpg', img2Url:'/stew/chicken-stew-2.jpg',  sortOrder:15 },
      { id:'16', name:'Beef Stew',            price:30000, category:'Stews', description:'Classic Nigerian beef stew with blended tomatoes and aromatic spices. 2L bowl.',             badge:'2L Bowl',    badgeColor:null,      imgUrl:'/stew/beef-stew-1.jpg',    img2Url:'/stew/beef-stew-2.jpg',     sortOrder:16 },
      { id:'17', name:'Fish Stew',            price:35000, category:'Stews', description:'Tomato-based stew with fresh, well-seasoned fish pieces. 2L bowl.',                         badge:'2L Bowl',    badgeColor:null,      imgUrl:'/stew/fish-stew-1.jpg',    sortOrder:17 },
      { id:'18', name:'Ofada Sauce',          price:45000, category:'Stews', description:'Authentic Ofada sauce with ayamase pepper blend. Perfect with ofada rice. 2L bowl.',        badge:'Fan Fav',    badgeColor:'#F97316', imgUrl:'/stew/ofada-sauce-1.jpg',  img2Url:'/stew/ofada-sauce-2.jpg',   sortOrder:18 },
      { id:'19', name:'Ofe Akwu (Banga)',     price:35000, category:'Stews', description:'Palm nut stew Urhobo style — great with boiled rice or yam. 2L bowl.',                     badge:'2L Bowl',    badgeColor:null,      imgUrl:'/stew/ofe-akwu-1.jpg',     sortOrder:19 },

      // ── RICE & POTTAGE (20–24) ─────────────────────────────────────────
      { id:'20', name:'Smokey Jollof Rice 3L', price:22000, category:'Rice & Pottage', description:'Our signature smokey party jollof — 3 litres with 5 pcs beef/chicken included.',  badge:'Bestseller', badgeColor:'#F97316', note:'Includes 5pcs beef/chicken', imgUrl:'/food/smokey-jollof.jpg',    img2Url:'/food/jollof-rice-bowl.jpg', sortOrder:20 },
      { id:'21', name:'Smokey Jollof Rice 5L', price:35000, category:'Rice & Pottage', description:'Party size jollof rice — 5 litres with 5 pcs beef/chicken. Feeds a crowd.',        badge:'Party Size', badgeColor:'#8B5CF6', note:'Includes 5pcs beef/chicken', imgUrl:'/food/jollof-rice-bowl.jpg', img2Url:'/food/smokey-jollof.jpg',    sortOrder:21 },
      { id:'22', name:'Fried Rice 3L',         price:28000, category:'Rice & Pottage', description:'Wok-fried Nigerian fried rice loaded with vegetables and protein. 3 litres.',                                              note:'Includes 5pcs beef/chicken', imgUrl:'/food/fried-rice-1.jpg',    img2Url:'/food/fried-rice-2.jpg',     sortOrder:22 },
      { id:'23', name:'Fried Rice 5L',         price:40000, category:'Rice & Pottage', description:'Large portion wok-fried rice for events. 5 litres with protein.',                 badge:'Party Size', badgeColor:'#8B5CF6', note:'Includes 5pcs beef/chicken', imgUrl:'/food/fried-rice-2.jpg',    img2Url:'/food/fried-rice-1.jpg',     sortOrder:23 },
      { id:'24', name:"Eddy's Pottage 3L",     price:15000, category:'Rice & Pottage', description:"Our chef's signature yam pottage — 3 litres, slow-cooked with panla fish.",      badge:'Chef Special',badgeColor:'#D97706', note:'Includes 5pcs panla fish',   imgUrl:'https://images.unsplash.com/photo-1600335895229-6e75511892c8?w=600&q=80', sortOrder:24 },

      // ── PASTA & RICE (25–33) ───────────────────────────────────────────
      { id:'25', name:'Creamy Chicken Pasta',       price:12000, category:'Pasta & Rice', subcat:'Pasta', description:'Silky cream sauce, perfectly seasoned chicken — Italian comfort with Nigerian soul.',  badge:'Popular',   badgeColor:'#F97316', imgUrl:'/food/creamy-chicken-pasta-1.jpg', img2Url:'/food/creamy-chicken-pasta-2.jpg', sortOrder:25 },
      { id:'26', name:'Nigerian Jollof Spaghetti',  price:9000,  category:'Pasta & Rice', subcat:'Pasta', description:'Smokey jollof-seasoned spaghetti with juicy chicken on the side.',                                                         imgUrl:'/food/jollof-spag-1.jpg',          img2Url:'/food/jollof-spag-2.jpg',          sortOrder:26 },
      { id:'27', name:'Shrimp Pasta',               price:15000, category:'Pasta & Rice', subcat:'Pasta', description:'Plump shrimp in a rich buttery sauce over perfectly cooked pasta.',                                                        imgUrl:'/food/shrimp-pasta-1.jpg',         img2Url:'/food/shrimp-pasta-2.jpg',         sortOrder:27 },
      { id:'28', name:'Asun Pasta',                 price:12000, category:'Pasta & Rice', subcat:'Pasta', description:'Smokey peppered goat meat tossed with pasta — bold Lagos flavours.',                  badge:'Spicy 🌶', badgeColor:'#DC2626', imgUrl:'/food/asun-pasta-1.jpg',           img2Url:'/food/asun-pasta-2.jpg',           sortOrder:28 },
      { id:'29', name:'Basmati Jollof Rice',        price:9000,  category:'Pasta & Rice', subcat:'Rice',  description:'Aromatic long-grain basmati in signature jollof sauce with chicken.',                                                       imgUrl:'/food/basmati-jollof.jpg',         img2Url:'/food/jollof-rice-bowl.jpg',       sortOrder:29 },
      { id:'30', name:'Special Basmati Fried Rice', price:12000, category:'Pasta & Rice', subcat:'Rice',  description:'Wok-tossed basmati with mixed vegetables, egg and chicken.',                                                               imgUrl:'/food/basmati-fried-rice.jpg',     img2Url:'/food/seafood-fried-rice.jpg',     sortOrder:30 },
      { id:'31', name:'Basmati Coconut Rice',       price:12000, category:'Pasta & Rice', subcat:'Rice',  description:'Creamy coconut-infused basmati with perfectly seasoned chicken.',                                                           imgUrl:'/food/coconut-rice.jpg',           img2Url:'/food/basmati-rice.jpg',           sortOrder:31 },
      { id:'32', name:'Native Nigerian Rice',       price:9000,  category:'Pasta & Rice', subcat:'Rice',  description:'Traditional ofada-style rice with rich palm oil sauce and assorted.',                                                       imgUrl:'/food/native-rice.jpg',                                                        sortOrder:32 },
      { id:'33', name:'Spicy Asun Rice',            price:9000,  category:'Pasta & Rice', subcat:'Rice',  description:'Jollof rice crowned with smoky peppered asun goat meat.',                             badge:'Spicy 🌶', badgeColor:'#DC2626', imgUrl:'/food/spicy-asun-rice.jpg',        img2Url:'/food/asun-rice.jpg',              sortOrder:33 },

      // ── FOOD BOXES (34–42) ─────────────────────────────────────────────
      { id:'34', name:'Classic Box',           price:15000, category:'Food Boxes', description:'A hearty classic box — your choice of protein with rice or swallow and a side.',                                                        imgUrl:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80', sortOrder:34 },
      { id:'35', name:'Deluxe Box',            price:30000, category:'Food Boxes', description:'Premium proteins, extra sides and a refreshing drink included.',                         badge:'Popular',     badgeColor:'#F97316', imgUrl:'/package/deluxe-box-1.jpg',  img2Url:'/package/deluxe-box-2.jpg',  sortOrder:35 },
      { id:'36', name:'Premium Box',           price:45000, category:'Food Boxes', description:'Our finest box — large portions, premium cuts, dessert included.',                      badge:'Best Value',  badgeColor:'#D97706', imgUrl:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=80', sortOrder:36 },
      { id:'37', name:'Breakfast Box',         price:28000, category:'Food Boxes', description:'Start your morning right — eggs, bread, sausage, plantain and fresh juice.',           badge:'Morning ☀️', badgeColor:'#F59E0B', imgUrl:'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=600&q=80', sortOrder:37 },
      { id:'38', name:'Treat Box',             price:20000, category:'Food Boxes', description:'Special curated box — perfect for gifting or treating yourself.',                                                                      imgUrl:'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&q=80',   sortOrder:38 },
      { id:'39', name:'Moimoi in Leaves 12pc', price:18000, category:'Food Boxes', description:'12 pieces of authentic leaf-wrapped moimoi with egg or fish inside.',                                        note:'With egg or fish', imgUrl:'/package/moimoi-1.jpg',                                                       sortOrder:39 },
      { id:'40', name:'Lunch Pack Mini',       price:4500,  category:'Food Boxes', description:'Mini lunch pack — great for office orders. Minimum 6 packs.',                          badge:'Bulk Order',  badgeColor:null,      note:'Min. 6 packs', imgUrl:'/package/lunch-mini-1.jpg',                                                   sortOrder:40 },
      { id:'41', name:'Lunch Pack Regular',    price:7000,  category:'Food Boxes', description:'Regular lunch pack with satisfying portions. Minimum 6 packs.',                        badge:'Bulk Order',  badgeColor:null,      note:'Min. 6 packs', imgUrl:'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=600&q=80', sortOrder:41 },
      { id:'42', name:'Small Chops Pack',      price:3500,  category:'Food Boxes', description:'Assorted small chops — puff puff, spring rolls, samosa. Min. 6 packs.',                                     note:'Min. 6 packs', imgUrl:'https://images.unsplash.com/photo-1506354666786-959d6d497f1a?w=600&q=80', sortOrder:42 },
    ],
  })

  console.log('✅ Seeded 42 menu items successfully!')
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())